### ISSUE TITLE
Link To theFirehoseProject

### ISSUE THREAD

**Issue by colinrubbert** [FirehoseCommunity/community.thefirehoseproject.com#12]
# Navbar Link To [theFirehoseProject](http://www.thefirehoseproject.com/)

**Comment by chaudhary27** [comment]
Link added.

**Comment by yvoloshin** [comment]
On the flip side, would be great to have a link to the community page from the student page sidebar at http://www.thefirehoseproject.com/courses, next to the existing links to our facebook and G+ pages. @kenmazaika?

**Comment by colinrubbert** [comment]
@yvoloshin I addressed that with Marco in my exit interview and I believe he added it to their to-do list but I'm sure @kenmazaika can either confirm or deny it. I agree 100% though, it would be very beneficial and helpful.

**Comment by kenmazaika** [comment]
I'll cross link this post to the ticket we have open on our side about this.

**Comment by dvanetten03** [comment]
I just checked and this is done, can we close it?

**Comment by kenmazaika** [comment]
Sure!
