### ISSUE TITLE
Improve The Navbar

### ISSUE THREAD

**Issue by colinrubbert** [FirehoseCommunity/community.thefirehoseproject.com#15]
# Navbar Needs Some More Work

**Comment by ghost** [comment]
Made some changes and sent in a PR. I'll keep an eye on the PR and look to take more issues on, but I want to give others a chance to address some issues too. I'll check back in some time.

Thanks for setting all this up @colinrubbert

**Comment by colinrubbert** [comment]
Thanks for jumping on this and making some improvements. I'll be working on trying to find more to do with the community page and I've got some ideas for more complex apps directed towards community projects. Check back and see if there are any new issues and if no one has tackled any for awhile you're welcome to take a stab at them. 

Thanks again for contributing!
