### ISSUE TITLE
As a Student I don't know how to contribute to the community page

### ISSUE THREAD

**Issue by MarcoMorawec** [FirehoseCommunity/community.thefirehoseproject.com#36]
Currently, a students who comes to the community page, does not know how to contribute to it.

I suggest we link to this excellent blog post (http://community.thefirehoseproject.com/2015/08/19/How-To-Fork-A-Repo-And-Contribute.html) directly in the top-nav. 

And it's probably a good idea to make that link stand out against all the other links (it is a call-to-action) after all.

**Comment by colinrubbert** [comment]
Excellent idea! I can start thinking about how we can make it standout amongst the other links. This would be an awesome addition for a student!

**Comment by jonathanpike** [comment]
This can be closed as it was addressed in #44

**Comment by colinrubbert** [comment]
Thanks for the heads up.
