### ISSUE TITLE
Restyle without theme

### ISSUE THREAD

**Issue by colinrubbert** [FirehoseCommunity/community.thefirehoseproject.com#8]
The installation and getting started with the current Jekyll theme can be over complicated with a lot of errors. I'm running into configuration errors with nodejs, npm, and grunt js during the setup process of the site. 

With the complexity and consistency of the issues with this particular theme I suggest that we start from scratch and try to implement a more simplistic option so that it will be easier for students to contribute. 

I propose that we start from bare bones Jekyll and build our features up from there. This way if there is a feature or styling that we want we can open up an issue and then assign them to Firehose students, if they want to work on it, to fix the issue and as a result be able to say they contributed to an open source project. This will hopefully also incentivize students to participate more heavily in the community Firehose page. 

I will start to build something out from scratch or rather on top of my Jekyll lightning talk demo since that was basically a from scratch project with some of our existing features built on top of it. From there I will submit the demo and we can decide if this is a route that we want to take to further expand and develop the community Firehose page.

**Comment by kenmazaika** [comment]
One thing I think is a little bit important is the design is _pretty good_.  Doesn't have to be amazing, but just not really noticeable.

Sad, but true, people will judge technical abilities of the author based off the presentation of the post.  If we build the theming from scratch, I think we should spend some time making it look pretty good (and design is hard and I'm not very good at it!)

Things that are really important to get right are:
- Whitespace
- Typography
- Colors

If we go the route of not using a pre-made theme we'll probably need to spend some time getting it to look good.

**Comment by colinrubbert** [comment]
I agree with that 100% I'm working on getting a demo to a point where it's pretty similar as what we have currently. It could be an excellent opportunity for a student with some design chops to contribute :grin: 

I'm going to work on it for a little bit longer and fix some of the nagging issues that I've got right now and then I'll share what I got going. I've already done a lot of leg room to get things looking good like they already do. It will give a great base for someone who is a much better designer than me to come in and make it GREAT!

**Comment by kenmazaika** [comment]
Perfect!

**Comment by colinrubbert** [comment]
Here's what I got so far. I'd say 70% of the current site's styling is copied over. I'd like to maybe get the post title/images in but that I will have to do much more tinkering with or get someone who is a better designer than I to get everything working.

We need to setup new fonts for everything too so it looks a bit cleaner but that could be a good project for a student to handle, something easy they can work with. All styling is also being pulled in via cdn links which may not always be the best approach but I thought we could leave adding the bootstrap, font awesome, and jquery inclusions for students to add if they so feel inclined to. 

Let me know what you think, everything is on my personal github.io page for simplicity sake if you want to take a look at the raw code too. Here's the link to the website http://colinrubbert.github.io/ and link to the repo https://github.com/colinrubbert/colinrubbert.github.io.

**Comment by kenmazaika** [comment]
I think it looks solid.  

Only thought it maybe the top-nav could be improved?  I have a couple different ways I played with in the inspector.

![screen shot 2015-08-13 at 5 35 11 pm](https://cloud.githubusercontent.com/assets/233615/9262309/f2041d28-41e1-11e5-8d62-02b0c524ed1d.png)

Black might not be the ideal color, maybe a blue or something would look better?

Maybe something like this?
![screen shot 2015-08-13 at 5 41 56 pm](https://cloud.githubusercontent.com/assets/233615/9262401/adceddc2-41e2-11e5-8a43-b754b816809e.png)

I don't know if these are better or worse.  I think what you have here is solid, just throwing out a couple ideas.

Feel free to ship what you have!

**Comment by kenmazaika** [comment]
Are you planning to force push your repo ontop of this one to eliminate the theme commits?  Feel free to do that if you want.

**Comment by colinrubbert** [comment]
The navbar was the next thing I wanted to tackle (I had the same thought) but I have been at this for a few hours now, I just need to step away haha

I figured what I will do is submit a branch (so there's a record of the redesign) and then we can merge it right over the top of the of our current site. That will give me some time to update the README file as well for installation.

I've been working on my laptop in Linux so I wanted to test in vagrant as well before we go nuts and tell everyone it's ready again to contribute to.

**Comment by kenmazaika** [comment]
Oh cool, I just checked your repo.  I assumed you worked off the old code (without the theme), but you actually ripped the new theme out instead of starting without the theme to begin with.  That makes git-fu easy.

Thumbs up!

**Comment by colinrubbert** [comment]
Alright, still didn't change the color of the navbar but I adjusted a bunch of styling to make it look a little better. I also added a hero image box to display the images that we have on the site. Everything is coming along nicely, I pulled to my vagrant box and that worked without issue. I think we can push to the primary site for the time being and add some issues for students to work on if they so choose to. Let me know what you think http://colinrubbert.github.io/.

**Comment by kenmazaika** [comment]
Looks great to me!

**Comment by colinrubbert** [comment]
Awesome, I'll merge it today on a separate branch and submit a pull request for final approval before merging to master.

**Comment by kenmazaika** [comment]
@MarcoMorawec might have some feedback too.  

One piece of super nitty-gritty design feedback is that on a wide screen, the lines are wide.  A former student dinged us on that on the old design of our lessons and told us that "It's hard to read on wide screens, and students might be making errors following the lessons because they have a hard time to read it.

Since he's given us that feedback I've been pretty attuned to width of text pages on various sites.

I'd suggest wrapping the content of the blog post in something like this to make it easier to read:

```
<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
```

For the videos, it's not a big deal.  For the blog posts, like the one you wrote, it matters a bit more.

Just my 2 cents.  Feel free to take it or leave it.  What you have now is excellent.

**Comment by colinrubbert** [comment]
Marco said the same thing yesterday, it's on my todo list of changes to be made. I changed the initial index page to reflect that width but noticed that I didn't do it to the actual posts after I pushed it. I will do that today as well before I push it.

**Comment by kenmazaika** [comment]
Nice!

**Comment by kenmazaika** [comment]
Fixed.  #9
